### ISSUE TITLE
Firmware Effect Packets

### ISSUE THREAD

**Issue by Shakesbeard** [node-lifx/lifx-lan-client#23]
I cannot contribute this at the moment because am deep into other stuff but if possible could someone kind add the packet files for the firmware effects here: https://lan.developer.lifx.com/docs/firmware-effects

**Comment by Shakesbeard** [comment]
Suprise haha, I actually started working on this myself. But for now only for the SetMultiZoneEffect - 508 command.
For multizone tiles there is currently only one effect anyways. So I will skip all the unused fields. This might need extension at some point if LIFX adds more effects for multizone devices.

I have not looked into the Tile firmware effects, yet.

**Comment by Shakesbeard** [comment]
@mabels maybe you got an idea. I have added that one single command. Updated the packet array and the packet index.js and derrived the new packet from setWaveform.
Everything also still works but if I try to send the new package I get this:
`dgram.js:312
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "buffer" argument must be one of type Buffer, Uint8Array, or string
    at sliceBuffer (dgram.js:312:11)
    at Socket.send (dgram.js:394:14)
    at Timeout._onTimeout (/node_modules/lifx-lan-client/lib/lifx/client.js:301:27)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

And I don't know what it wants to tell me.
The packat is being created but when sending it BAM :( 
I don't get why it should not be a buffer. Any idea what I could search for?

**Comment by Shakesbeard** [comment]
I do suspect this to be fishy but I don't know:
  utils.writeUInt64LE(buf, offset, obj.duration);
  offset += 8;

**Comment by Shakesbeard** [comment]
Hah! Works. Silly mistake on my end. But the duration cannot be set as I have no support for Int64. Otherwise this works.

**Comment by Shakesbeard** [comment]
Added with pull https://github.com/node-lifx/lifx-lan-client/pull/24 

Firmware effects for Tiles not included, this is only for the multizone devices
